### PR TITLE
Threadsafe - ConcurrentDictionary instead of IDictionary

### PR DESCRIPTION
**Pull request by Tasteful**
The Dictionary that is used internal for cache is not threadsafe. Updated to use ConcurrentDictionary instead.

### CODE REVIEW

**Comment by TylerCarlson1** [comment]
Is this fix intended for 3.3.1 AutoMapper compatible and not 4.2.1 AutoMapper compatible?  Because that's the one that's being updated.

I need to do some cleanup with the branches it seems.

**Comment by Tasteful** [comment]
Good question :) I was creating a new clean fork of you and was changing from master, the automapper version that I got out is AutoMapper.4.0.4.

The changes is only in private methods so I don't think the version of AutoMapper is relevant.

**Comment by TylerCarlson1** [comment]
Ok yea the master would work on 4.0.4 I believe.  In development it's for 4.2.0+ because of IObjectMapper changed IsMatch to pass TypePair and not ResolutionContext.

Also development has a ConcurrentDictionary in one place to handle Thread Safe issues.

I'll have to look at it more but most likely what I might do is release the 1.1.3 and then merge development into master.

**Comment by TylerCarlson1** [comment]
[1.1.3](https://www.nuget.org/packages/AutoMapper.Collection/1.1.3)

Master is now merged with Development and is 1.2.1 code base (AM 4.2.1+) compatible.
Also tagged the versions in Source Control

**Pull request merged**
